version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=demo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  rabbitmq:
    image: rabbitmq:management-alpine
    environment:
      - RABBITMQ_DEFAULT_VHOST=demo_vhost
      - RABBITMQ_DEFAULT_USER=demo
      - RABBITMQ_DEFAULT_PASS=demo
    ports:
      - "5672:5672"
      - '15672:15672'
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_NAME=demo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - RABBITMQ_DEFAULT_VHOST=demo_vhost
      - RABBITMQ_DEFAULT_USER=demo
      - RABBITMQ_DEFAULT_PASS=demo
    depends_on:
      - db
      - mongo
      - rabbitmq
  worker:
    image: demo-web
    volumes:
      - .:/code
    command: python -m celery -A demo worker -l info
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_NAME=demo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - RABBITMQ_DEFAULT_VHOST=demo_vhost
      - RABBITMQ_DEFAULT_USER=demo
      - RABBITMQ_DEFAULT_PASS=demo
    depends_on:
      - web
  beat:
    image: demo-web
    volumes:
      - .:/code
    command: python -m celery -A demo beat -l info
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_NAME=demo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - RABBITMQ_DEFAULT_VHOST=demo_vhost
      - RABBITMQ_DEFAULT_USER=demo
      - RABBITMQ_DEFAULT_PASS=demo
    depends_on:
      - web
  flower:
    image: demo-web
    volumes:
      - .:/code
    command: python -m celery -A demo flower
    ports:
      - "5555:5555"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_NAME=demo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - RABBITMQ_DEFAULT_VHOST=demo_vhost
      - RABBITMQ_DEFAULT_USER=demo
      - RABBITMQ_DEFAULT_PASS=demo
    depends_on:
      - web
